### ISSUE TITLE
We need more tests on the functions. e.g. WHAT THE MODEL DO WHEN SEX IS Unknown?

### ISSUE THREAD

**Issue by ibartomeus** [liamkendall/pollimetry#10]
See bodysize function for notes.

**Comment by liamkendall** [comment]
Do you think the function needs any more tests?

I thought about writing in the function to add a column of Sex if it didn't exist (all with Female for example) but couldn't figure out how to add a column to x within the function

**Comment by ibartomeus** [comment]
I don't think you should fix users problems (e.g. write for them code), but you should have clear warnings an ensure they can not use the package wrong (e.g. do something iffy without a warning). See /tests folder when I started to document potential user behaviors and the results... I added notes where better warning messages are needed.
