### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by liamkendall** [liamkendall/pollimetry#11]
CRAN submission before or after submission? @ibartomeus

**Comment by ibartomeus** [comment]
I think it is irrelevant. CRAN process should be faster than the paper anyway. Before submitting to CRAN check ropensci advise on how to succeed as I know they are very picky. I don't think we are in a rush to submit to CRAN, so take your time to polish the help files, etc... Also, do you plan to publish a preprint? I think would be nice.
