### ISSUE TITLE
bee tongue length raw data

### ISSUE THREAD

**Issue by liamkendall** [liamkendall/pollimetry#12]
@ibartomeus I think we should draw in raw data and compute these internally - give users S.E. and 95% CIs

`data(tongues)`
`proboscis=lm(log(mean_tongue_length_mm)~log(mean_IT_length_mm)+Family,tongues)`
`glossa=lm(log(mean_glossa_length_mm)~log(mean_IT_length_mm)+Family,tongues)`
`prementum=lm(log(mean_prementum_length_mm)~log(mean_IT_length_mm)*Family,tongues)`

I got the data from traitbase, are the formulae correct? results differ slightly from paper

**Comment by liamkendall** [comment]
check out - `tonguelength2` - if you like it, then ill replace `tonguelength`

**Comment by ibartomeus** [comment]
Cool! Two things. 1st, you should add a unit test that makes travis.ci fail if data change location. I have no intention to move the data, but if you depend on external packages is good to cover your back with an automated test. 2nd, what "slightly" means? I checked the exact model we used, and yours looks correct. The issue may be that we select only females, while your data may pool males and females, not sure. If the estimates are very similar, I will go with it. Or ask Dan for the data filtered exactly as in the paper. However, if our idea is to add more data when available to this models too, I will go with it.

**Comment by liamkendall** [comment]
Ok, not sure how to make such a test, could you help?
I can always subset the models to only use females but by slightly I meant the R2 were much the same, just AIC were a little different.
Shall I go ahead and replace `tonguelength`?

**Comment by ibartomeus** [comment]
Check how similar are the estimates. Yes, go ahead, but then we should add to the paper /help that this is not longer Cariveus original equations, but a re-implementation. 

We will talk later about unit testing. It's listed in another issue.
