### ISSUE TITLE
Bee nectar load allometry

### ISSUE THREAD

**Issue by liamkendall** [liamkendall/pollimetry#13]
Thoughts on including this? @ibartomeus @louissutter 
 
Allometry of maximal field nectar load in bees - See Figure S4

Maximal nectar load = 0.005 * Body length ^ 3.0618

https://www.nature.com/articles/s41598-018-27591-y#Sec11

https://static-content.springer.com/esm/art%3A10.1038%2Fs41598-018-27591-y/MediaObjects/41598_2018_27591_MOESM1_ESM.pdf

I might ask for the raw data so we can compute SE and CI's

Would also be cool to do the same for pollen loads

**Comment by ibartomeus** [comment]
Sure, sounds interesting!

**Comment by liamkendall** [comment]
function written and ready to be implemented in next update
