### ISSUE TITLE
Package size

### ISSUE THREAD

**Issue by liamkendall** [liamkendall/pollimetry#6]
Package size is too large for CRAN. Waiting on response from brms developer.

Another option: https://journal.r-project.org/archive/2017/RJ-2017-026/index.html

**Comment by ibartomeus** [comment]
Yes, or load the data from an external server within the function, but both options still need to load 50 Mb of data (which is slow-ish) and if we can reduce this would be better.

**Comment by liamkendall** [comment]
See thread: http://discourse.mc-stan.org/t/reducing-brms-model-output-size-for-predictive-function/4903
As far as I could make out (`save_dso=FALSE`) didn't work for me and running stan natively will have the same issues of size: the models take too long to run so it'll be a lot slower to make the function run the fit internally.

I think external package may be the way to go: each model is only ~15mb so the function will only have to load one each time to run

**Comment by louissutter** [comment]
I am not familiar with the brms model architecture, but not we need the entire 15mb from each model? or would it be possible to extract the parameters we need for prediction without loading the entire model?

**Comment by liamkendall** [comment]
We/Nacho had a go at this but the `$fit` object which is needed for the predictions contains the majority of the file size... Extracting the parameters is an option but this goes beyond my knowledge in regard to keeping the random effect structure in the predictions... I'm open to the idea though!
Ill have a go at making an external data package and then run some speed tests on the function

**Comment by ibartomeus** [comment]
I asked a friend and suggested to apply "thinning" to reduce the number of posterior simulations saved. 

I am inclined to save the model outputs in the cloud and call them when necessary from the function. Maybe figshare is a good place for storing it? Or maybe directly from github?

**Comment by ibartomeus** [comment]
ok, we can add a note that loading is slow, and go with it. Thanks. 

PS: Note the bodysize function is broken now, I think you need to remove an "else" section, but I let you handle this.

**Comment by liamkendall** [comment]
Its working for me? Both with and without the data package - where does it stop for you?

**Comment by ibartomeus** [comment]
Now it's working, maybe I had an older version loaded, sorry.
